# Generated by Django 3.0.6 on 2020-05-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Тираж',
                'verbose_name_plural': 'Тираж',
            },
        ),
        migrations.CreateModel(
            name='Colorfulness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorfulness', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Красочность',
                'verbose_name_plural': 'Красочность',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paper', models.CharField(max_length=40)),
                ('density', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Тип бумаги',
                'verbose_name_plural': 'Тип бумаг',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукции',
            },
        ),
        migrations.CreateModel(
            name='TypePrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_print', models.CharField(max_length=40)),
                ('colorfulness', models.ManyToManyField(to='core.Colorfulness')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Circulation')),
                ('paper', models.ManyToManyField(to='core.Paper')),
                ('production', models.ManyToManyField(to='core.Production')),
            ],
            options={
                'verbose_name': 'Вид печати',
                'verbose_name_plural': 'Виды печати',
            },
        ),
    ]
