# Generated by Django 3.0.6 on 2020-05-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulation',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='colorfulness',
            name='colorfulness',
            field=models.CharField(max_length=15, verbose_name='Красочность'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='density',
            field=models.IntegerField(blank=True, verbose_name='Плотность бумаги'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='type_paper',
            field=models.CharField(max_length=40, verbose_name='Тип бумаги'),
        ),
        migrations.AlterField(
            model_name='production',
            name='name_product',
            field=models.CharField(max_length=35, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='typeprint',
            name='name_print',
            field=models.CharField(max_length=40, verbose_name='Тип печати'),
        ),
    ]
