# Generated by Django 3.0.6 on 2020-05-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200514_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='density',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плотность бумаги'),
        ),
    ]
