# Generated by Django 3.0.6 on 2020-05-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200517_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TypePrint'),
        ),
    ]
